<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-jesusrincon1328/blob/main/Module_5_Working_with_Numpy_Arrays_%26_Simple_APIs_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Importar la libreria numpy
import numpy as np

In [8]:
#Crear numpy array
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [9]:
#como en una lista podemos acceder a cada elemento a traves de square bracket
print("a[0]:",a[0])
print("a[1]:",a[1])
print("a[1]:",a[2])
print("a[1]:",a[3])
print("a[1]:",a[4])

a[0]: 0
a[1]: 1
a[1]: 2
a[1]: 3
a[1]: 4


In [10]:
#revisar la version de numpy
print(np.__version__)

1.21.6


In [11]:
#Revisar el tipo de array
type(a)


numpy.ndarray

In [12]:
#obtener el tipo de valores que contiene el numpy array con la funcion "dtype"
a.dtype

dtype('int64')

In [13]:
#realizar otro ejemplo con la funcion "dtype"
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b.dtype

dtype('float64')

In [14]:
#cambiar un valor en el array
c=np.array([20,1,2,3,4])
c

array([20,  1,  2,  3,  4])

In [17]:
#asignar valor 100 al primer elemento
c[0]= 100
c

array([100,   1,   2,   3,   4])

In [19]:
#cambiar el 5to elemento a 0
c[4]=0
c

array([100,   1,   2,   3,   0])

In [20]:
#asignar el valor de 20 al segundo elemento en el siguiente array
a = np.array([10, 2, 30, 40,50])
a[1] = 20
a

array([10, 20, 30, 40, 50])

**Slicing**
Como en las listas, podemos tomar parte de un array de acuerdo al index y formar uno nuevo. [inicio:fin]

In [21]:
#tomar parte de un array
d = c[1:4]
d

array([1, 2, 3])

In [23]:
#cambiar el cuarto y quinto elemento de C por 300 y 400
c[3:5] = 400,500
c

array([100,   1,   2, 400, 500])

In [24]:
#tabien podemos definir steps/brincos de la siguiente manera [inicio,fin,step]
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [26]:
#si no colocamos el incio lo considera como 0
print(arr[:4])

[1 2 3 4]


In [27]:
#si no colocamos el fin considera del inicio indicado hasta el final del array
print(arr[4:])

[5 6 7]


In [28]:
#si no colocamos el numero de step considera 1
print(arr[1:5:])

[2 3 4 5]


In [31]:
#imprime los numeros pares del siguiente arreglo
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:8:2])


[2 4 6 8]


In [32]:
#podemos utilizar una lista para seleccionar mas de un index especifico, considera la siguiente lista
select = [0,2,3,4]
select

[0, 2, 3, 4]

In [33]:
d = c[select]
d

array([100,   2, 400, 500])

In [34]:
#podemos asignar un valor a los eslementos especificos de select
c[select]=100000
c

array([100000,      1, 100000, 100000, 100000])

**Otros atributos**

In [35]:
#considera el siguiente array a:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [36]:
#El atributo size es el numero de elementos del array
a.size


5